probar fallo de seguridad de nuevo

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -23,5 +23,10 @@ jobs:
 
             - name: Revisar seguridad basica
               run: |
-                 grep -T "eval(" .&& exit 1 || echo "Sin uso de eval)"    
+                   if grep -R "eval(" script.js; then
+                        echo "ERROR: se detecto eval()"
+                        exit 1
+                    else
+                        echo "Seguridad OK"
+                    fi   
 
